services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: api_hospital
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432

  account:
    depends_on:
      - postgres-db
    build:
      context: ./account
    container_name: account
    ports:
      - 8001:8000
    environment:
      DEBUG: True
      DB_NAME: api_hospital
      DB_USER: postgres
      DB_PASSWORD: postgres1234
      DB_HOST: postgres-db
      DB_PORT: 5432

  hospital:
    depends_on:
      - postgres-db
    build:
      context: ./hospital
    container_name: hospital
    ports:
      - 8002:8000
    environment:
      DEBUG: True
      DB_NAME: api_hospital
      DB_USER: postgres
      DB_PASSWORD: postgres1234
      DB_HOST: postgres-db
      DB_PORT: 5432

  timetable:
    depends_on:
      - postgres-db
    build:
      context: ./timetable
    container_name: timetable
    ports:
      - 8003:8000
    environment:
      DEBUG: True
      DB_NAME: api_hospital
      DB_USER: postgres
      DB_PASSWORD: postgres1234
      DB_HOST: postgres-db
      DB_PORT: 5432

  document:
    depends_on:
      - postgres-db
    build:
      context: ./document
    container_name: document
    ports:
      - 8004:8000
    environment:
      DEBUG: True
      DB_NAME: api_hospital
      DB_USER: postgres
      DB_PASSWORD: postgres1234
      DB_HOST: postgres-db
      DB_PORT: 5432